### ISSUE TITLE
Multiple path support

### ISSUE THREAD

**Issue by matz3** [expressjs/serve-index#24]
Hi,

is there any plan in supporting multiple paths to be used for a directory index?
A use case is when you have multiple directories which are served under the same path by using [serve-static](https://github.com/expressjs/serve-static) like this:
```js
app.use('/foo', serveStatic('public1'));
app.use('/foo', serveStatic('public2'));

app.use('/foo', serveIndex([ 'public1', 'public2' ]));
```

**Comment by matz3** [comment]
I had a look into this and saw that the feature would require to change the parameters of the [`html`](https://github.com/expressjs/serve-index/blob/7381a1d1458959e57ee53ac932b06ff17904777e/index.js#L167) method (at least the parameter types, because the file stat has to be done in multiple dirs).
The method gets exported, so I guess it's public API and this would be an incompatible change.
Another option would be to pass different parameters depending on multiple or single paths.

I would like to have your opinion on this before starting to code.

**Comment by dougwilson** [comment]
Hi @matz3 ! So as far as public API breakage, that is OK, so just work on that assumption. Once we have some PR, we can make a judgement of can it be made backwards-compatible or not and just live with that outcome :) This library is building up plenty of 2.0 things, so that would just nudge a 2.0 release (especially since Express 3.x is being discontinued, which is the only reason this module has been sticking to 1.x).

**Comment by matz3** [comment]
Thanks, so I'll go ahead 👍

**Comment by dougwilson** [comment]
Closing for now, as per https://github.com/expressjs/serve-index/pull/29#issuecomment-112578713
