### ISSUE TITLE
Display content in existing HTML?

### ISSUE THREAD

**Issue by SterlingButters** [expressjs/serve-index#96]
Is there a way to display the index in some existing HTML?

**Comment by dougwilson** [comment]
Hi @SterlingButters ! Without knowing more about what you're asking, it sounds like you just want to show the index in some existing HTML you already have and not with the template this module provides. This is done through the `template` option: https://github.com/expressjs/serve-index#template

**Comment by SterlingButters** [comment]
Hey @dougwilson Thanks for such a quick response!! Is there any high-level example on how to do this?

**Comment by dougwilson** [comment]
Not currently, but you're welcome to contribute one :) !

**Comment by SterlingButters** [comment]
Well I'm just afraid I don't understand the explanation in the docs :/

**Comment by dougwilson** [comment]
I'm happy to help come up with an example for you, but I just need to understand what you're trying to do in order to make a relevant example.

**Comment by SterlingButters** [comment]
Thank you so much!

So what I need is really quite simple I think. My server structure looks like this:

- app.js
- index.html
- uploads
   - <files>

And I am just trying to list the files under uploads using my index.html. So ideally there would be some way to just add a sort of iFrame that displays the content of serve-index (if that makes sense)?

**Comment by dougwilson** [comment]
Ah. If you use this module like `app.use('/uploads', serveIndex(__dirname + '/uploads'))` in your `app.js`, then you'll get all the indexs located under `/uploads` (basically the example https://github.com/expressjs/serve-index#serve-directory-indexes-with-express with the directory name different for your naming).

Then as for doing the iframe, you can just add like `<iframe src=/uploads></iframe>` in your `index.html` since that will be the location of your listrings.
